[package]
name = "annealing"
version = "0.1.0"
authors = ["den"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
rand_chacha = "0.2.1"
image = "0.22.3"
imageproc = "0.19.2"
priority-queue = "0.6.0"
